# Generated by Django 5.0.6 on 2024-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myurl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='uid',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
